### ISSUE TITLE
KRB Error: (7) KDC_ERR_S_PRINCIPAL_UNKNOWN Server not found in Kerberos database - UNKNOWN_SERVER

### ISSUE THREAD

**Issue by applee** [Sqooba/hdfs#14]
Why the error ignored here? If I catch the error, I got it as the title above.
https://github.com/Sqooba/hdfs/blob/461efab7d5ca69b20f4484e52cd6a78eb2e4c93a/rpc/namenode.go#L354-L356

**Comment by Shastick** [comment]
Thanks for the remark: it's a mistake and should definitively be a stopper and be returned.

The present master branch is still be a bit buggy: things are getting fixed in the PR branch for the hdfs library.

**Comment by Shastick** [comment]
Closing -> cleanup.
